//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetToolkit.Repository.AdoNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetToolkit.Repository.AdoNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be null or an empty string..
        /// </summary>
        internal static string ArgumentCannotBeNullOrEmptyString {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string does not exist in your configuration file..
        /// </summary>
        internal static string ConnectionStringDoestNotExistInConfigFile {
            get {
                return ResourceManager.GetString("ConnectionStringDoestNotExistInConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instance of entity type &apos;{0}&apos; cannot be added to the database because another instance of this type with the same key is already being tracked..
        /// </summary>
        internal static string EntityAlreadyBeingTrackedInStore {
            get {
                return ResourceManager.GetString("EntityAlreadyBeingTrackedInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to update or delete an entity that does not exist in the database..
        /// </summary>
        internal static string EntityNotFoundInStore {
            get {
                return ResourceManager.GetString("EntityNotFoundInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column name {0} is not valid..
        /// </summary>
        internal static string InvalidColumnName {
            get {
                return ResourceManager.GetString("InvalidColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model backing the &apos;{0}&apos; context has changed since the database was created. Consider updating the database..
        /// </summary>
        internal static string SchemaTableColumnsMismatch {
            get {
                return ResourceManager.GetString("SchemaTableColumnsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve DbProviderFactory for: {0.
        /// </summary>
        internal static string UnableToRetrieveDbProviderFactoryForm {
            get {
                return ResourceManager.GetString("UnableToRetrieveDbProviderFactoryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Provider Factory specified: {0}.
        /// </summary>
        internal static string UnsupportedProviderFactory {
            get {
                return ResourceManager.GetString("UnsupportedProviderFactory", resourceCulture);
            }
        }
    }
}
